spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  flyway:
    baselineOnMigrate: true
  jpa:
    hibernate:
      ddl-auto: update
